/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.northeastern.cs5500.backend.controller;

import static com.google.common.truth.Truth.assertThat;

import edu.northeastern.cs5500.backend.model.User;
import edu.northeastern.cs5500.backend.repository.InMemoryRepository;
import org.junit.jupiter.api.Test;

class UserControllerTest {
    User createTestUser(String emailAddress, String password) {
        User user = new User();
        user.setEmailAddress(emailAddress);
        user.setPassword(password);
        return user;
    }

    @Test
    void testCanAddUser() {
        // This test should NOT call register
        // TODO: implement this test.
    }

    @Test
    void testCanReplaceUser() {
        // This test should NOT call register
        // TODO: implement this test.
    }

    @Test
    void testCanDeleteUser() {
        // This test should NOT call register
        // TODO: implement this test
    }

    @Test
    void testCanGetUserByEmailAddress() throws Exception {
        final String emailAddress = "a@b.com";
        final String otherEmailAddress = "c@d.com";
        UserController uC = new UserController(new InMemoryRepository<User>());
        User user = uC.addUser(createTestUser(emailAddress, "password1"));
        User otherUser = uC.addUser(createTestUser(otherEmailAddress, "password2"));

        // Make sure that we aren't just getting the same user
        assertThat(user).isNotEqualTo(otherUser);

        // Make sure we're getting the specific user we requested
        assertThat(uC.getUserByEmailAddress(emailAddress)).isEqualTo(user);
        assertThat(uC.getUserByEmailAddress(otherEmailAddress)).isEqualTo(otherUser);
    }
}
