/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.northeastern.cs5500.backend.controller;

import static com.google.common.truth.Truth.assertThat;
import static com.google.common.truth.Truth.assertWithMessage;

import edu.northeastern.cs5500.backend.model.User;
import edu.northeastern.cs5500.backend.repository.InMemoryRepository;
import org.junit.jupiter.api.Test;

class UserControllerTest {
    @Test
    void testRegisterCreatesUser() {
        UserController UserController = new UserController(new InMemoryRepository<User>());
        assertThat(UserController.getUser()).isNotEmpty();
    }

    @Test
    void testRegisterCreatesValidUser() {
        UserController UserController = new UserController(new InMemoryRepository<User>());

        for (User user : UserController.getUser()) {
            assertWithMessage(user.getUsername()).that(user.isValid()).isTrue();
        }
    }

    @Test
    void testCanAddUser() {
        // This test should NOT call register
        // TODO: implement this test.
    }

    @Test
    void testCanReplaceUser() {
        // This test should NOT call register
        // TODO: implement this test.
    }

    @Test
    void testCanDeleteUser() {
        // This test should NOT call register
        // TODO: implement this test
    }
}
