/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.northeastern.cs5500.backend;

import dagger.Component;
import edu.northeastern.cs5500.backend.model.ModelModule;
import edu.northeastern.cs5500.backend.repository.RepositoryModule;
import edu.northeastern.cs5500.backend.view.View;
import edu.northeastern.cs5500.backend.view.ViewModule;
import java.util.Set;
import javax.inject.Inject;
import javax.inject.Singleton;

@Component(
        modules = {
            ViewModule.class,
            ModelModule.class,
            RepositoryModule.class,
        })
@Singleton
interface ServerComponent {
    public Server server();
}

public class Server {

    @Inject Set<View> views;

    @Inject
    Server() {}

    void start() {
        for (View view : views) {
            view.register();
        }
    }
}
